version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: celebre-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: celebre_db
    ports:
      - '5432:5432'
    volumes:
      - celebre_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d celebre_db']
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  celebre_pg_data:
